name: Kali CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build and Push
        run: |
          podman pull docker.io/kalilinux/kali-rolling
          podman login -u ${{ secrets.GHCR_UNAME }} -p ${{ secrets.GHCR_PAT }} ghcr.io
          podman build . -t ghcr.io/sir-mudkip/kali:latest
          podman push ghcr.io/sir-mudkip/kali:latest
